export { default as Login } from './auth/Login';
export { default as Register } from './auth/Register';
export { default as Home } from './Home';
export { default as Transaksi } from './Transaksi';
export { default as Pengambilan } from './Pengambilan';
export { default as Status } from './Status';
export { default as NewBussiness } from './NewBussiness';
export { default as Pelanggan } from './Pelanggan';
export { default as PelangganDetail } from './PelangganDetail';